### ISSUE TITLE
Jora, Yarn and Nodejs

### ISSUE THREAD

**Issue by obenjiro** [lahmatiy/jora#6]
error jora@1.0.0-alpha.10: The engine "node" is incompatible with this module. Expected version "^8.0.0". Got "11.14.0"

**Comment by lahmatiy** [comment]
Ouch, it should be `>=8.0.0`. Can you send a PR?

**Comment by obenjiro** [comment]
Fixed in #8

**Comment by lahmatiy** [comment]
Thanks!
